### ISSUE TITLE
pretrain weights

### ISSUE THREAD

**Issue by wang-qinliang** [dqj5182/CONTHO_RELEASE#1]
Why it be an Archive folder after decompression of contho_demo.pth.tar. I haven't seen the contho_demo.pth file. Where should I find the weight file?

**Comment by dqj5182** [comment]
Thanks for your interest in our work!

You don't need to decompress the checkpoint files `contho_demo.pth.tar` file to run our code. For example, you can run our demo code as follows:
`python main/demo.py --gpu 0 --checkpoint contho_demo.pth.tar`

Hope this answered your question :)

**Comment by wang-qinliang** [comment]
Thank you for your answer. Following your guidance, I have encountered another problem.
I'm very sorry to disturb you.

Traceback (most recent call last):
  File "/work_sdb/wql03/wql/data/CONTHO_RELEASE/main/demo.py", line 6, in <module>
    from utils.img_utils import load_demo_inputs
  File "/work_sdb/wql03/wql/data/CONTHO_RELEASE/main/../lib/utils/img_utils.py", line 9, in <module>
    from models.templates import obj_dict
  File "/work_sdb/wql03/wql/data/CONTHO_RELEASE/main/../lib/models/templates.py", line 236, in <module>
    smplh = SMPLH()
  File "/work_sdb/wql03/wql/data/CONTHO_RELEASE/main/../lib/models/templates.py", line 17, in __init__
    self.layer = {'neutral': smplx.create(self.model_path, 'smplh', gender='NEUTRAL', **self.layer_arg), 'male': smplx.create(self.model_path, 'smplh', gender='MALE', **self.layer_arg), 'female': smplx.create(self.model_path, 'smplh', gender='FEMALE', **self.layer_arg)}
  File "/work_sdb/wql03/wql/envs/contho/lib/python3.9/site-packages/smplx/body_models.py", line 2410, in create
    raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type human, exiting!

**Comment by dqj5182** [comment]
No worries!

According to the error, I think you did not download human model file.
The human model file should be in `human_models` folder of `base_data` that I have shared as a [Google Drive](https://drive.google.com/drive/folders/1f0RYWHrCfaegEG24lcuP7-5PfsHGrchj?usp=sharing) link in readme file.

I recommend downloading the `base_data` from [Google Drive](https://drive.google.com/drive/folders/1f0RYWHrCfaegEG24lcuP7-5PfsHGrchj?usp=sharing) and move the folder under `data` just like the directory structure of `data` mentioned in readme file.
