### ISSUE TITLE
Demo issues

### ISSUE THREAD

**Issue by DamianMYM** [dqj5182/CONTHO_RELEASE#2]
Hi, 

First of all, Thank you for your great work! 

I wanna try your demo codes and encountered some issues.  I wanna know if you met the following error.
`RuntimeError: Subtraction, the `-` operator, with a bool tensor, is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.`

I actually tried to modify the torchgeometry module based on the error log, however,  I only got some .obj files which I cannot open. What is the normal output situation instead?

<img width="874" alt="image" src="https://github.com/dqj5182/CONTHO_RELEASE/assets/113518689/cccbd2c2-8540-46b7-85da-1b3d4b042f27">

Looking forward to your reply.
Many thanks,
Damian

**Comment by dqj5182** [comment]
Thank you for your interest!

Actually, the error is a very common issue of a specific python package that we are using.

I have referred to a solution on the issue in readme. Please feel free to check readme and ask additional question if needed!

**Comment by DamianMYM** [comment]
Thank you for your quick response. It seems like I didn't modify it successfully and missed your Q&A part of README. 
Thank you again.
