### ISSUE TITLE
How to downsample the new object?

### ISSUE THREAD

**Issue by kunkun0w0** [dqj5182/CONTHO_RELEASE#3]
Thanks for releasing this amazing work!!!

I want to train CONTHO on my dataset. But I don't know how to convert the new object mesh into 64 key points, as in your paper. Would you like to share that script or any reference? 

Thanks so much!!!

**Comment by dqj5182** [comment]
Thank you for your interest in our work!

We conducted K-nearest neighbors (KNN) algorithm on vertices of the object mesh.
Specifically, our implementation was based upon [scikit-learn](https://scikit-learn.org/stable/)'s KNN implementation.
Our belief was that this is the simplest and the most intuitive way of down-sampling object mesh vertices.

Depending on your circumstances, I think you could also use random sampling or learning-based approach for keypoint extraction (i.e., [KeypointNet (NeurIPS 2018)](https://keypointnet.github.io/)) for downsampling object mesh vertices.

Hope my answer helped!

**Comment by kunkun0w0** [comment]
Thanks for your suggestion!
