### ISSUE TITLE
Regarding bounding boxes

### ISSUE THREAD

**Issue by ac5113** [dqj5182/CONTHO_RELEASE#4]
Congratulations on the project!
I wanted to enquire regarding the bounding boxes that you use as input to the demo. Are these the human bboxes or the human+object bboxes?

**Comment by dqj5182** [comment]
Hi! Thanks for your complement :)
The bounding boxes are human+object bboxes provided by BEHAVE dataset.

Note that the format of bbox is [x_min, y_min, width, height].

**Comment by ac5113** [comment]
Thank you for the information!
