### ISSUE TITLE
Regarding object id

### ISSUE THREAD

**Issue by flacy7** [dqj5182/CONTHO_RELEASE#5]
Thanks for releasing the amazing work!
I want to enquire regarding the object id. You use it as input, so does it mean we need to know in advance what objects are in the image when we use this model?

**Comment by dqj5182** [comment]
Thanks for your interest in our work!

You are correct.
It is necessary for our model to know object id (or category) in advance. 

For real-world application, I recommend you to use CONTHO as follows:
1) When you have a fixed set of objects to be reconstructed
: This is useful in scenarios when applied in manufacturing line in factories. As the manufacturing line has fixed set of objects to be handled, it is useful to just focus on accurately reconstructing 3D human and object.
2) When you deal with arbitrary categories of object
: This may not perform well as this is not tested in our experiments. But, you can use off-the-shelf object detectors (i.e., YOLO) to extract object id (or category) and use it to give object id for CONTHO.

**Comment by flacy7** [comment]
Thanks for answering!
