### ISSUE TITLE
Regarding loss computation

### ISSUE THREAD

**Issue by ac5113** [dqj5182/CONTHO_RELEASE#7]
Hello,
I wanted to check what the results would be if the GT contacts were passed to CRFormer. However, the output human and object contacts returned by ContactFormer [here](https://github.com/dqj5182/CONTHO_RELEASE/blob/4b34405dca9aaefb5ca7436884d4153aa5eb4c61/lib/models/model.py#L67) do not match the gt human and object contact shapes. Was the contact loss computed on two different output and target shapes?

**Comment by dqj5182** [comment]
We downsample the human and object vertices for more efficient computation.

In CONTHO code, you can see that human mesh vertices are downsampled [here](https://github.com/dqj5182/CONTHO_RELEASE/blob/4b34405dca9aaefb5ca7436884d4153aa5eb4c61/lib/models/model.py#L47) and we call the downsampled object vertices [here](https://github.com/dqj5182/CONTHO_RELEASE/blob/4b34405dca9aaefb5ca7436884d4153aa5eb4c61/lib/models/model.py#L53).

Under the same downsampling procedure, you can downsample the GT contacts and pass them to CRFormer.
Regarding how to downsample object vertices, please check the previous [issue](https://github.com/dqj5182/CONTHO_RELEASE/issues/3).

**Comment by ac5113** [comment]
Thank you for the response!
Please correct me if I'm wrong, but the h_contacts predicted by the CONTHO model is of shape (B, 431)
However, the [GT](https://github.com/dqj5182/CONTHO_RELEASE/blob/4b34405dca9aaefb5ca7436884d4153aa5eb4c61/lib/dataset/base_dataset.py#L82) that it is compared with is of shape (B, 6890)
And I cannot find any GT preprocessing before the [loss computation](https://github.com/dqj5182/CONTHO_RELEASE/blob/4b34405dca9aaefb5ca7436884d4153aa5eb4c61/lib/core/base.py#L52)

**Comment by dqj5182** [comment]
You are correct.

What you are missing is that we have already downsampled the annotated contact when creating our base_data (e.g., behave_train.json)
That is why you cannot find downsampling process within the loss computation.
